name: build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: setup-linux
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get install librtmidi-dev jackd libjack0 libjack-dev

    - name: setup-macos
      if: matrix.os == 'macos-latest'
      run: |
        sw_vers -productVersion
        brew install rtmidi

    - name: setup 
      run: |
        luarocks install inspect

    - name: build-linux
      if: matrix.os == 'ubuntu-22.04'
      run: |
        set -e
        lua -v
        luarocks make rockspecs/lrtmidi-scm-0.rockspec
        lua -e 'print(require"lrtmidi"); print(require"lrtmidi"._VERSION)'
        lua -e 'print("RtMidi", require"lrtmidi".getRtMidiVersion());'

    - name: build-macos
      if: matrix.os == 'macos-latest'
      run: |
        set -e
        lua -v
        luarocks make CC="gcc" LD="gcc" rockspecs/lrtmidi-scm-0.rockspec
        lua -e 'print(require"lrtmidi"); print(require"lrtmidi"._VERSION)'
        lua -e 'print("RtMidi", require"lrtmidi".getRtMidiVersion());'

    - name: test-linux
      if: matrix.os == 'ubuntu-22.04'
      run: |
        set -e
        lua -v
        jackd -r -ddummy -r44100 -p1024 &
        sleep 2
        echo "=============================================="
        lua examples/example01.lua
     
    - name: test-macos
      if: matrix.os == 'macos-latest'
      run: |
        set -e
        lua -v
        echo "=============================================="
        lua examples/example01.lua
